---
title: High-throughput identification of genotype-specific cancer vulnerabilities
  in mixtures of barcoded tumor cell lines
author: "zijian"
date: '2020-04-06'
slug: high-throughput-identification-of-genotype-specific-cancer-vulnerabilities-in-mixtures-of-barcoded-tumor-cell-lines
tags:
- high throughput screeing
- Cancer drug discovery
categories: cancer
---
# Title
>High-throughput identification of genotype-specific cancer vulnerabilities   in mixtures of barcoded tumor cell lines

# Citaion
>Yu C, Mannan AM, Yvone GM, et al. High-throughput identification of genotype-specific cancer vulnerabilities in >mixtures of barcoded tumor cell lines. Nat Biotechnol. 2016;34(4):419–423. doi:10.1038/nbt.3460

# Abstract 

>Hundreds of genetically characterized cell lines are available for the discovery of genotype-specific cancer >vulnerabilities. However, screening large numbers of compounds against large numbers of cell lines is currently >impractical, and such experiments are often difficult to control1-4. Here, we report a method called PRISM that allows >pooled screening of mixtures of cancer cell lines by labeling each cell line with 24-nucleotide barcodes. PRISM >displayed the expected patterns of cell killing seen in conventional (unpooled) assays. In a screen of 102 cell lines >across 8,400 compounds, PRISM led to the identification of BRD-7880 as a potent and highly specific inhibitor of aurora >kinases B and C. Cell line pools also efficiently formed tumors as xenografts, and PRISM recapitulated the expected >pattern of erlotinib sensitivity in vivo

# Take home Message
>